import React from 'react'
import Ajv from 'ajv'
import { Button, ButtonToolbar, Collapse, FormGroup, FormControl, ControlLabel, HelpBlock } from 'react-bootstrap'
import $ from 'jquery'
import ResumeSchema from '../public/schema'

export default React.createClass({
  getInitialState() {
    return {
      value: this.props.initialValue,
      isValid: true,
      isEditable: false,
      isDirty: false
    }
  },
  handleReset() {
    this.setState(this.getInitialState())
    this.props.onReset()
  },
  getValidationState() {
    if (this.state.isValid) {
      return 'success'
    } else {
      return 'error'
    }
  },
  validateJSON(text) {
    try {
      var parsed = JSON.parse(text)
      var ajv = new Ajv({ useDefaults: true })
      var validate = ajv.compile(ResumeSchema)
      var valid = validate(parsed)

      if (!valid) {
        this.setState({ isValid: false })
        this.setState({ parseErrorMessage: 'JSON does not conform to schema' })
        // console.log(validate.errors)
        return
      }

      this.setState({ isValid: true })
      return parsed
    } catch (e) {
      this.setState({ isValid: false })
      this.setState({ parseErrorMessage: 'Invalid JSON' })
    }
  },
  handleChange(e) {
    this.setState({ value: e.target.value, isDirty: true })
    let parsed = this.validateJSON(e.target.value)
    if (parsed) {
      this.props.onChangeHandler(parsed)
    }
  },
  toggleEdit() {
    this.setState({ isEditable: !this.state.isEditable })
  },
  handleCollapseOnEntering() {
    $('html, body').animate({ scrollTop: $(document).height() }, 400)
  },
  render: function() {
    return (
      <div style={{ fontSize: 12, textAlign: 'center', padding: 5 }} className='footer-block'>
          This site's content was generated by a JSON resumé. <a onClick={ ()=> this.setState({ open: !this.state.open }) }>View it here</a> or try your own!
        <Collapse in={ this.state.open } onEntering={ this.handleCollapseOnEntering }>
          <div style={{ padding: 15 }} className='section group'>
            <form>
              <FormGroup
                controlId="formBasicText"
                validationState={ this.getValidationState() }>

                  <div className='col span_1_of_2'>
                    <FormControl componentClass="textarea"
                                 className='json'
                                 placeholder="textarea"
                                 value={ this.state.value }
                                 onChange={ this.handleChange }
                                 disabled={ !this.state.isEditable } />
                  </div>
                  <div className='col span_1_of_2' style={{ textAlign: 'left' }}>
                    Paste your JSON resume here. It must conform to <a href="/public/schema.json">the schema.</a>
                    <br />
                    You can check your JSON against a <a href="http://www.jsonschemavalidator.net">JSON Schema Validator</a>
                    <HelpBlock>
                    <br />
                    { this.state.isValid ? '✅ Valid JSON!' : this.state.parseErrorMessage }</HelpBlock>
                    <ButtonToolbar>
                      <Button bsSize="small" onClick={ this.toggleEdit }> { this.state.isEditable ? 'Lock' : 'Unlock' }</Button>
                      <Button bsSize="small" onClick={ this.handleReset }>Reset Resumé</Button>
                      <Button bsSize="small" onClick={ ()=> this.setState({ open: !this.state.open }) }>Close Section</Button>
                    </ButtonToolbar>
                    <br />
                  </div>
              </FormGroup>
            </form>
          </div>
        </Collapse>
      </div>
    )
  }
})